/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/signin": {
    /**
     * Авторизация с помощью email и пароля 
     * @description Отправляет запрос на авторизацию с email и паролем.
     */
    post: operations["signInWithPassword"];
  };
  "/auth/confirm": {
    /**
     * Подтверждение регистрации с помощью кода 
     * @description Отправляет запрос на подтверждение с помощью шестизначного кода.
     */
    post: operations["confirmSignUp"];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Авторизация с помощью email и пароля 
   * @description Отправляет запрос на авторизацию с email и паролем.
   */
  signInWithPassword: {
    requestBody: {
      content: {
        "application/json": {
          /**
           * Format: email 
           * @example user@example.com
           */
          email: string;
          /** @example P@ssword123 */
          password: string;
        };
      };
    };
    responses: {
      /** @description Успешная авторизация */
      200: {
        content: {
          "application/json": {
            /** @example Code sent successfully */
            message?: string;
            /**
             * Format: numeric 
             * @example 395781
             */
            confirmationCode?: string;
          };
        };
      };
      /** @description Ошибка авторизации */
      400: {
        content: {
          "application/json": {
            /** @example Invalid credentials */
            error?: string;
          };
        };
      };
    };
  };
  /**
   * Подтверждение регистрации с помощью кода 
   * @description Отправляет запрос на подтверждение с помощью шестизначного кода.
   */
  confirmSignUp: {
    requestBody: {
      content: {
        "application/json": {
          /** @example 123456 */
          confirmationCode: string;
        };
      };
    };
    responses: {
      /** @description Успешное подтверждение */
      200: {
        content: {
          "application/json": {
            /** @example Account confirmed successfully */
            message?: string;
          };
        };
      };
      /** @description Неправильный код подтверждения */
      400: {
        content: {
          "application/json": {
            /** @example Incorrect verification code */
            error?: string;
          };
        };
      };
    };
  };
}
